/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tratamentos: Tratamento;
    resultados: Resultado;
    depoimentos: Depoimento;
    faq: Faq;
    leads: Lead;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tratamentos: TratamentosSelect<false> | TratamentosSelect<true>;
    resultados: ResultadosSelect<false> | ResultadosSelect<true>;
    depoimentos: DepoimentosSelect<false> | DepoimentosSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    clinica: Clinica;
    seo: Seo;
    rastreamento: Rastreamento;
  };
  globalsSelect: {
    clinica: ClinicaSelect<false> | ClinicaSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    rastreamento: RastreamentoSelect<false> | RastreamentoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tratamentos".
 */
export interface Tratamento {
  id: number;
  titulo: string;
  /**
   * Usado na ancora da pagina. Exemplo: queda-capilar
   */
  slug: string;
  resumo: string;
  descricao?: string | null;
  imagem?: (number | null) | Media;
  indicacoes?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  ordem?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva a imagem para leitores de tela e para o Google.
   */
  alt: string;
  legenda?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resultados".
 */
export interface Resultado {
  id: number;
  titulo: string;
  antes: number | Media;
  depois: number | Media;
  meses?: number | null;
  tratamento?: (number | null) | Tratamento;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "depoimentos".
 */
export interface Depoimento {
  id: number;
  nome: string;
  texto: string;
  nota: number;
  tratamento?: (number | null) | Tratamento;
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  pergunta: string;
  resposta: string;
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  nome: string;
  email?: string | null;
  whatsapp: string;
  motivo: 'queda-capilar' | 'alopecia' | 'caspa-dermatite' | 'tricoscopia' | 'outro';
  mensagem?: string | null;
  /**
   * Preenchido automaticamente pelos parametros UTM.
   */
  origem?: {
    utm_source?: string | null;
    utm_medium?: string | null;
    utm_campaign?: string | null;
    utm_content?: string | null;
    utm_term?: string | null;
    pagina?: string | null;
  };
  status?: ('novo' | 'em-contato' | 'agendado' | 'perdido') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nome: string;
  /**
   * Administrador ve os leads e gerencia usuarios. Editor so cuida do conteudo do site.
   */
  papel: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tratamentos';
        value: number | Tratamento;
      } | null)
    | ({
        relationTo: 'resultados';
        value: number | Resultado;
      } | null)
    | ({
        relationTo: 'depoimentos';
        value: number | Depoimento;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tratamentos_select".
 */
export interface TratamentosSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumo?: T;
  descricao?: T;
  imagem?: T;
  indicacoes?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  ordem?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resultados_select".
 */
export interface ResultadosSelect<T extends boolean = true> {
  titulo?: T;
  antes?: T;
  depois?: T;
  meses?: T;
  tratamento?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "depoimentos_select".
 */
export interface DepoimentosSelect<T extends boolean = true> {
  nome?: T;
  texto?: T;
  nota?: T;
  tratamento?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  pergunta?: T;
  resposta?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  nome?: T;
  email?: T;
  whatsapp?: T;
  motivo?: T;
  mensagem?: T;
  origem?:
    | T
    | {
        utm_source?: T;
        utm_medium?: T;
        utm_campaign?: T;
        utm_content?: T;
        utm_term?: T;
        pagina?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  legenda?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  papel?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinica".
 */
export interface Clinica {
  id: number;
  nome: string;
  chamada?: string | null;
  logo?: (number | null) | Media;
  /**
   * Só tem efeito em bloco com dois arquivos ou mais.
   */
  heroIntervalo?: number | null;
  /**
   * O bloco grande. O primeiro arquivo é o que carrega primeiro.
   */
  heroPainel?:
    | {
        arquivo: number | Media;
        id?: string | null;
      }[]
    | null;
  heroBlocoEsquerda?:
    | {
        arquivo: number | Media;
        id?: string | null;
      }[]
    | null;
  heroBlocoDireita?:
    | {
        arquivo: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Texto miúdo que abre a grade, à esquerda do resumo.
   */
  sobreRotulo?: string | null;
  /**
   * Parágrafo curto, em cinza. Duas ou três linhas.
   */
  sobreResumo?: string | null;
  /**
   * O bloco grande, em destaque. É o que sustenta a seção.
   */
  sobre?: string | null;
  /**
   * Foto larga, atravessa a página inteira. Ideal por volta de 2000 por 900.
   */
  foto?: (number | null) | Media;
  /**
   * Aparece pequeno e redondo, ao lado do nome. Rosto centralizado.
   */
  retrato?: (number | null) | Media;
  nomeProfissional?: string | null;
  /**
   * A linha sob o nome. Exemplo: Tricologista clínica.
   */
  credencial?: string | null;
  /**
   * Somente números, com DDI e DDD. Exemplo: 5511999999999
   */
  whatsapp: string;
  mensagemWhatsapp?: string | null;
  email?: string | null;
  /**
   * Para onde vai o aviso de cada cadastro do formulário. Vazio, usa o e mail acima.
   */
  emailAvisoLead?: string | null;
  /**
   * Apenas o usuário, sem arroba.
   */
  instagram?: string | null;
  /**
   * Fica ao lado do formulário, em pé. O cartão de contato cobre a parte de baixo, então evite rosto na borda inferior.
   */
  fotoAgendamento?: (number | null) | Media;
  unidades?:
    | {
        nome: string;
        endereco: string;
        telefone?: string | null;
        mapaUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  horarios?: string | null;
  metricas?:
    | {
        /**
         * Exemplo: 1.200+
         */
        valor: string;
        rotulo: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  /**
   * Ate 60 caracteres. Comece pela palavra chave principal.
   */
  titulo: string;
  /**
   * Ate 155 caracteres. E o texto que aparece no resultado de busca.
   */
  descricao: string;
  /**
   * Usadas para orientar os textos das secoes. Nao entram como meta keywords, que o Google ignora desde 2009.
   */
  palavrasChave?:
    | {
        termo: string;
        id?: string | null;
      }[]
    | null;
  imagemCompartilhamento?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rastreamento".
 */
export interface Rastreamento {
  id: number;
  /**
   * Formato GTM-XXXXXXX. E o container principal.
   */
  gtmId?: string | null;
  /**
   * Formato G-XXXXXXXXXX. Deixe vazio se o GA4 ja dispara pelo GTM.
   */
  ga4Id?: string | null;
  /**
   * Somente numeros. Deixe vazio se o pixel ja dispara pelo GTM.
   */
  metaPixelId?: string | null;
  /**
   * Formato AW-XXXXXXXXX, para conversoes de anuncio.
   */
  googleAdsId?: string | null;
  /**
   * Disparado quando o formulario e enviado com sucesso.
   */
  googleAdsLabelLead?: string | null;
  /**
   * Com a opcao ligada o site inicia em modo negado e so libera medicao e anuncios apos o aceite, seguindo a LGPD e o Consent Mode v2.
   */
  consentimento?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinica_select".
 */
export interface ClinicaSelect<T extends boolean = true> {
  nome?: T;
  chamada?: T;
  logo?: T;
  heroIntervalo?: T;
  heroPainel?:
    | T
    | {
        arquivo?: T;
        id?: T;
      };
  heroBlocoEsquerda?:
    | T
    | {
        arquivo?: T;
        id?: T;
      };
  heroBlocoDireita?:
    | T
    | {
        arquivo?: T;
        id?: T;
      };
  sobreRotulo?: T;
  sobreResumo?: T;
  sobre?: T;
  foto?: T;
  retrato?: T;
  nomeProfissional?: T;
  credencial?: T;
  whatsapp?: T;
  mensagemWhatsapp?: T;
  email?: T;
  emailAvisoLead?: T;
  instagram?: T;
  fotoAgendamento?: T;
  unidades?:
    | T
    | {
        nome?: T;
        endereco?: T;
        telefone?: T;
        mapaUrl?: T;
        id?: T;
      };
  horarios?: T;
  metricas?:
    | T
    | {
        valor?: T;
        rotulo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  titulo?: T;
  descricao?: T;
  palavrasChave?:
    | T
    | {
        termo?: T;
        id?: T;
      };
  imagemCompartilhamento?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rastreamento_select".
 */
export interface RastreamentoSelect<T extends boolean = true> {
  gtmId?: T;
  ga4Id?: T;
  metaPixelId?: T;
  googleAdsId?: T;
  googleAdsLabelLead?: T;
  consentimento?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}